
# SEO settings
title: "this"
title2: "FYP" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://lincerely.github.io/thisFYP # site url
baseurl: "/thisFYP" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/lincerely/thisFYP
disqus_shortname: "lincerely"
twitter_username: "lincerely"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Lincerely"
  job      : "Game Developer"
  bio      : "I love this profile pic."
  thumb    : /images/author.jpg
  email    : lincerely@gmail.com
  url      : http://lincerely.github.io
  github   : http://github.com/lincerely
  twitter  : http://twitter.com/lincerely
  facebook : https://www.facebook.com/lincolnlilinghin
  linkedin : http://www.linkedin.com/in/西芹-lincerely-4767b7a6

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@lincerely"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
